/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flapybird;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JApplet;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Flapy extends JApplet implements Runnable {

    /**
     * Initializes the applet Flapy
     */
    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    Topka krug;
    public void Flapy (){
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    
   
    @Override
    public void init()
    {  
       try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    main();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    public void main(){
        setSize(500, 500);
        krug = new Topka();
        this.getContentPane().add(krug);
        Thread anim = new Thread(this);
        anim.start();
    }
    void sleep(int n)
    {
        try {
           
            Thread.sleep(n);
        } catch (InterruptedException ex) {
            Logger.getLogger(Flapy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void run() {
    	repaint();
    	for (int i = 0; i < 3; i++)
    	{
    		
    		krug.dodajVreme(1000);
    		repaint();
    		sleep(1000);
            repaint();
    	}
    	krug.dodajVreme(1000);
        while (true)
        {
            this.repaint();
            sleep(20);
        }
       
    }
    int vreme = 0;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
